# For available configuration options, see:
#   https://github.com/standardrb/standard
ruby_version: 3.1

ignore:
  - '**/**/*':
    - Layout/SpaceAroundOperators
    - Layout/SpaceAroundOperators
    - Layout/SpaceInsideHashLiteralBraces
    - Naming/MethodParameterName
    - Style/IfInsideElse
    - Style/EmptyCaseCondition
    - Style/NestedTernaryOperator
    - Style/StringLiterals
    - Style/TernaryParentheses
    - Style/TrailingCommaInArguments
    - Style/TrailingCommaInArrayLiteral
    - Style/TrailingCommaInHashLiteral
    - Style/WhenThen
  - '**/**/ansi.rb':
    - Style/RedundantSelf
  - 'lib/road_to_rubykaigi/audio/audio_engine.rb':
    - Naming/VariableName
    - Security/Open
