# For available configuration options, see:
#   https://github.com/standardrb/standard
ruby_version: 3.1

ignore:
  - '**/**/*':
    - Layout/SpaceAroundOperators
    - Layout/SpaceAroundOperators
    - Layout/SpaceInsideHashLiteralBraces
    - Naming/MethodParameterName
    - Style/IfInsideElse
    - Style/EmptyCaseCondition
    - Style/StringLiterals
    - Style/TrailingCommaInArguments
    - Style/TrailingCommaInArrayLiteral
    - Style/TrailingCommaInHashLiteral
    - Style/WhenThen
  - '**/**/ansi.rb':
    - Style/RedundantSelf
  - '**/**/macos.rb':
    - Naming/ConstantName
    - Naming/VariableName
