# For available configuration options, see:
#   https://github.com/standardrb/standard
ruby_version: 3.1

ignore:
  - '**/**/*':
    - Layout/SpaceAroundOperators
    - Layout/SpaceAroundOperators
    - Layout/SpaceInsideHashLiteralBraces
    - Naming/MethodParameterName
    - Style/StringLiterals
    - Style/TrailingCommaInArguments
    - Style/TrailingCommaInArrayLiteral
    - Style/TrailingCommaInHashLiteral
  - '**/**/ansi.rb':
    - Style/RedundantSelf
